# Copyright 2016 Mobvoi Inc. All Rights Reserved.
# Author: xjliu@mobvoi.com (Xiaojia Liu)

package(default_visibility = ['//visibility:public'])

load("//third_party/protobuf:protobuf.bzl", "cc_proto_library")

cc_proto_library(
  name = 'kafka_meta_proto',
  srcs = [
    'kafka_meta.proto'
  ],
)
