CREATE TABLE `news_info` (
  `id` varchar(200) NOT NULL DEFAULT '',
  `url` varchar(400) NOT NULL DEFAULT '',
  `title` varchar(400) NOT NULL DEFAULT '',
  `content` text NOT NULL DEFAULT '',
  `category` varchar(100) NOT NULL DEFAULT '',
  `publish_source` varchar(100) NOT NULL DEFAULT '',
  `publish_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `summary` text NOT NULL DEFAULT '',
  `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `keywords` varchar(400) NOT NULL DEFAULT '',
  `tags` varchar(200) NOT NULL DEFAULT '',
  `image` varchar(400) NOT NULL DEFAULT '',
  `meta_publish_source` varchar(100) NOT NULL DEFAULT '',
  `meta_publish_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `data_utilization` varchar(100) NOT NULL DEFAULT '',
  `score` text NOT NULL DEFAULT '',
  `topic` varchar(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `url` (`url`),
  KEY `title` (`title`),
  KEY `updated` (`updated`),
  KEY `publish_time` (`publish_time`),
  KEY `meta_publish_time` (`meta_publish_time`),
  KEY `topic` (`topic`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
