# Copyright 2016 Mobvoi Inc. All Rights Reserved.
# Author: xjliu@mobvoi.com (Xiaojia Liu)

cc_binary(
  name = 'flight_query_test_main',
  srcs = [
    'flight_query_test_main.cc',
  ],
  deps = [
    '//base:base',
    '//third_party/jsoncpp',
    '//util/net/http_client:http_client',
    '//push/util:time_util',
  ],
)
