# Copyright 2016 Mobvoi Inc. All Rights Reserved.
# Author: xjliu@mobvoi.com (Xiaojia Liu)

package(default_visibility = ['//visibility:public'])

cc_library(
  name = 'train_push_processor',
  srcs = [
    'train_push_processor.h',
    'train_push_processor.cc',
  ],
  deps = [
    '//push/push_controller:push_processor'
  ]
)

