package(default_visibility = ['//visibility:public'])

load("//third_party/protobuf:protobuf.bzl", "cc_proto_library")

cc_proto_library(
  name = 'push_meta_proto',
  srcs = [
    'push_meta.proto'
  ],
)

cc_proto_library(
  name = 'weather_meta_proto',
  srcs = [
    'weather_meta.proto'
  ],
)

cc_proto_library(
  name = 'flight_meta_proto',
  srcs = [
    'flight_meta.proto'
  ],
)

cc_proto_library(
  name = 'train_meta_proto',
  srcs = [
    'train_meta.proto'
  ],
)

cc_proto_library(
  name = 'user_feedback_meta_proto',
  srcs = [
    'user_feedback_meta.proto'
  ],
)

cc_proto_library(
  name = 'birthday_meta_proto',
  srcs = [
    'birthday_meta.proto'
  ],
)

cc_proto_library(
  name = 'redis_meta_proto',
  srcs = [
    'redis_meta.proto'
  ],
)

cc_proto_library(
  name = 'message_receiver_meta_proto',
  srcs = [
    'message_receiver_meta.proto'
  ],
)

cc_proto_library(
  name = 'user_device_meta_proto',
  srcs = ['user_device_meta.proto'],
)
